services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: ./config/config.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - ":27017"
    volumes:
      - db:/data/db
  
  app:
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    env_file: ./config/config.env
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

volumes:
  db: